grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin

  service:
    type: LoadBalancer

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL

alertmanager:
  enabled: true

prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 15d
    scrapeInterval: 15s

    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
