[package]
name = "rating-catalog"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15"
tokio = { version = "1", features = ["full"] }
tonic = "0.14"
prost = "0.14"
tonic-prost = "0.14"
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres"] }
serde = "1.0.228"
prometheus = "0.13"
axum = "0.7"
lazy_static = "1"

[build-dependencies]
tonic-prost-build = "0.14"
protoc-bin-vendored = "3"
