services:
  rating-catalog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rating-catalog
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${HOST_GRPC_PORT}:${GRPC_PORT}"
    depends_on:
      - rating-db
      - rating-redis
    networks:
      - bookcloud-network

  rating-db:
    image: postgres:15
    container_name: rating-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${HOST_POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - rating-db-data:/var/lib/postgresql/data
    networks:
      - bookcloud-network

  rating-redis:
    image: redis:7
    container_name: rating-redis
    restart: unless-stopped
    ports:
      - "${HOST_REDIS_PORT}:${REDIS_PORT}"
    networks:
      - bookcloud-network

volumes:
  rating-db-data:

networks:
  bookcloud-network:
    external: true
