apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-redis
  namespace: bookcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: author-redis
  template:
    metadata:
      labels:
        app: author-redis
    spec:
      containers:
        - name: author-redis
          image: redis:7
          ports:
            - name: redis
              containerPort: 6379
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 15
            periodSeconds: 20
