syntax = "proto3";

package gateway.ratingcatalog;

import "common.proto";

service RatingCatalogGrpc {
  rpc HealthCheck(gateway.common.HealthCheckRequest) returns (gateway.common.HealthCheckResponse);

  rpc GetRating(GetRatingRequest) returns (GetRatingResponse);
  // rpc GetRatingBook(GetRatingBookRequest) returns (GetRatingBookRequest);
  // rpc CreateRating(CreateRatingRequest) returns (CreateRatingResponse);
  // rpc UpdateRating(UpdateRatingRequest) returns (UpdateRatingResponse);
  // rpc DeleteRating(DeleteRatingRequest) returns (DeleteRatingResponse);
}




// ----------------------------
// -------- GET RATING --------
// ----------------------------
message GetRatingRequest {
  string rating_id = 1;
}

message GetRatingResponse {
    string status = 1;
}

// // ---------------------------------
// // -------- GET RATING BOOK --------
// // ---------------------------------
// message GetRatingBookRequest {
//   string fileName = 1;
// }

// message GetRatingBookResponse {
//     bool service = 1;
//     string status = 2;
// }

// // -------------------------------
// // -------- CREATE RATING --------
// // -------------------------------
// message CreateRatingRequest {
//   string fileName = 1;
// }

// message CreateRatingResponse {
//     bool service = 1;
//     string status = 2;
// }

// // -------------------------------
// // -------- UPDATE RATING --------
// // -------------------------------
// message UpdateRatingRequest {
//   string fileName = 1;
// }

// message UpdateRatingResponse {
//   string fileName = 1;
// }

// // -------------------------------
// // -------- DELETE RATING --------
// // -------------------------------
// message DeleteRatingRequest {
//     bool service = 1;
//     string status = 2;
// }

// message DeleteRatingResponse {
//     bool service = 1;
//     string status = 2;
// }
