apiVersion: v1
kind: Service
metadata:
  name: compare-service
  namespace: bookcloud
spec:
  selector:
    app: compare-service
  ports:
    - name: grpc
      port: 50054
      targetPort: grpc
  type: ClusterIP
