services:
  book-catalog:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${HOST_GRPC_PORT}:${GRPC_PORT}"
    networks:
      - bookcloud-network
    depends_on:
      - book-db
      - book-redis

  book-db:
    image: postgres:15
    container_name: book-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${HOST_POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - book-db-data:/var/lib/postgresql/data
    networks:
      - bookcloud-network

  book-redis:
    image: redis:7
    container_name: book-redis
    restart: unless-stopped
    ports:
      - "${HOST_REDIS_PORT}:${REDIS_PORT}"
    networks:
      - bookcloud-network

volumes:
  book-db-data:

networks:
  bookcloud-network:
    external: true
