services:
  book-catalog:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      RUST_LOG: info
    ports:
      - "${HOST_GRPC_PORT}:50051"
    networks:
      - bookcloud-network

networks:
  bookcloud-network:
    external: true