# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import genre_service_pb2 as genre__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in genre_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GenreAnalysisGrpcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/gateway.genreservice.GenreAnalysisGrpc/HealthCheck',
                request_serializer=common__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=common__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetGenres = channel.unary_unary(
                '/gateway.genreservice.GenreAnalysisGrpc/GetGenres',
                request_serializer=genre__service__pb2.GetGenresRequest.SerializeToString,
                response_deserializer=genre__service__pb2.GetGenresResponse.FromString,
                _registered_method=True)
        self.AddGenre = channel.unary_unary(
                '/gateway.genreservice.GenreAnalysisGrpc/AddGenre',
                request_serializer=genre__service__pb2.AddGenreRequest.SerializeToString,
                response_deserializer=genre__service__pb2.AddGenreResponse.FromString,
                _registered_method=True)
        self.GetGenre = channel.unary_unary(
                '/gateway.genreservice.GenreAnalysisGrpc/GetGenre',
                request_serializer=genre__service__pb2.GetGenreRequest.SerializeToString,
                response_deserializer=genre__service__pb2.GetGenreResponse.FromString,
                _registered_method=True)
        self.UpdateGenre = channel.unary_unary(
                '/gateway.genreservice.GenreAnalysisGrpc/UpdateGenre',
                request_serializer=genre__service__pb2.UpdateGenreRequest.SerializeToString,
                response_deserializer=genre__service__pb2.UpdateGenreResponse.FromString,
                _registered_method=True)
        self.DeleteGenre = channel.unary_unary(
                '/gateway.genreservice.GenreAnalysisGrpc/DeleteGenre',
                request_serializer=genre__service__pb2.DeleteGenreRequest.SerializeToString,
                response_deserializer=genre__service__pb2.DeleteGenreResponse.FromString,
                _registered_method=True)
        self.AddGenreToBook = channel.unary_unary(
                '/gateway.genreservice.GenreAnalysisGrpc/AddGenreToBook',
                request_serializer=genre__service__pb2.AddGenreToBookRequest.SerializeToString,
                response_deserializer=genre__service__pb2.AddGenreToBookResponse.FromString,
                _registered_method=True)
        self.RemoveGenreFromBook = channel.unary_unary(
                '/gateway.genreservice.GenreAnalysisGrpc/RemoveGenreFromBook',
                request_serializer=genre__service__pb2.RemoveGenreFromBookRequest.SerializeToString,
                response_deserializer=genre__service__pb2.RemoveGenreFromBookResponse.FromString,
                _registered_method=True)
        self.GetGenreGrowth = channel.unary_unary(
                '/gateway.genreservice.GenreAnalysisGrpc/GetGenreGrowth',
                request_serializer=genre__service__pb2.GenreGrowthRequest.SerializeToString,
                response_deserializer=genre__service__pb2.GenreGrowthResponse.FromString,
                _registered_method=True)
        self.GetGenrePopularity = channel.unary_unary(
                '/gateway.genreservice.GenreAnalysisGrpc/GetGenrePopularity',
                request_serializer=genre__service__pb2.GenrePopularityRequest.SerializeToString,
                response_deserializer=genre__service__pb2.GenrePopularityResponse.FromString,
                _registered_method=True)
        self.GetBooksByGenre = channel.unary_unary(
                '/gateway.genreservice.GenreAnalysisGrpc/GetBooksByGenre',
                request_serializer=genre__service__pb2.GetBooksByGenreRequest.SerializeToString,
                response_deserializer=genre__service__pb2.GetBooksByGenreResponse.FromString,
                _registered_method=True)


class GenreAnalysisGrpcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGenres(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddGenre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGenre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGenre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteGenre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddGenreToBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveGenreFromBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGenreGrowth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGenrePopularity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBooksByGenre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenreAnalysisGrpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=common__pb2.HealthCheckRequest.FromString,
                    response_serializer=common__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetGenres': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGenres,
                    request_deserializer=genre__service__pb2.GetGenresRequest.FromString,
                    response_serializer=genre__service__pb2.GetGenresResponse.SerializeToString,
            ),
            'AddGenre': grpc.unary_unary_rpc_method_handler(
                    servicer.AddGenre,
                    request_deserializer=genre__service__pb2.AddGenreRequest.FromString,
                    response_serializer=genre__service__pb2.AddGenreResponse.SerializeToString,
            ),
            'GetGenre': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGenre,
                    request_deserializer=genre__service__pb2.GetGenreRequest.FromString,
                    response_serializer=genre__service__pb2.GetGenreResponse.SerializeToString,
            ),
            'UpdateGenre': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGenre,
                    request_deserializer=genre__service__pb2.UpdateGenreRequest.FromString,
                    response_serializer=genre__service__pb2.UpdateGenreResponse.SerializeToString,
            ),
            'DeleteGenre': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteGenre,
                    request_deserializer=genre__service__pb2.DeleteGenreRequest.FromString,
                    response_serializer=genre__service__pb2.DeleteGenreResponse.SerializeToString,
            ),
            'AddGenreToBook': grpc.unary_unary_rpc_method_handler(
                    servicer.AddGenreToBook,
                    request_deserializer=genre__service__pb2.AddGenreToBookRequest.FromString,
                    response_serializer=genre__service__pb2.AddGenreToBookResponse.SerializeToString,
            ),
            'RemoveGenreFromBook': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveGenreFromBook,
                    request_deserializer=genre__service__pb2.RemoveGenreFromBookRequest.FromString,
                    response_serializer=genre__service__pb2.RemoveGenreFromBookResponse.SerializeToString,
            ),
            'GetGenreGrowth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGenreGrowth,
                    request_deserializer=genre__service__pb2.GenreGrowthRequest.FromString,
                    response_serializer=genre__service__pb2.GenreGrowthResponse.SerializeToString,
            ),
            'GetGenrePopularity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGenrePopularity,
                    request_deserializer=genre__service__pb2.GenrePopularityRequest.FromString,
                    response_serializer=genre__service__pb2.GenrePopularityResponse.SerializeToString,
            ),
            'GetBooksByGenre': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBooksByGenre,
                    request_deserializer=genre__service__pb2.GetBooksByGenreRequest.FromString,
                    response_serializer=genre__service__pb2.GetBooksByGenreResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gateway.genreservice.GenreAnalysisGrpc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gateway.genreservice.GenreAnalysisGrpc', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GenreAnalysisGrpc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.genreservice.GenreAnalysisGrpc/HealthCheck',
            common__pb2.HealthCheckRequest.SerializeToString,
            common__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGenres(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.genreservice.GenreAnalysisGrpc/GetGenres',
            genre__service__pb2.GetGenresRequest.SerializeToString,
            genre__service__pb2.GetGenresResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddGenre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.genreservice.GenreAnalysisGrpc/AddGenre',
            genre__service__pb2.AddGenreRequest.SerializeToString,
            genre__service__pb2.AddGenreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGenre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.genreservice.GenreAnalysisGrpc/GetGenre',
            genre__service__pb2.GetGenreRequest.SerializeToString,
            genre__service__pb2.GetGenreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateGenre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.genreservice.GenreAnalysisGrpc/UpdateGenre',
            genre__service__pb2.UpdateGenreRequest.SerializeToString,
            genre__service__pb2.UpdateGenreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteGenre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.genreservice.GenreAnalysisGrpc/DeleteGenre',
            genre__service__pb2.DeleteGenreRequest.SerializeToString,
            genre__service__pb2.DeleteGenreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddGenreToBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.genreservice.GenreAnalysisGrpc/AddGenreToBook',
            genre__service__pb2.AddGenreToBookRequest.SerializeToString,
            genre__service__pb2.AddGenreToBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveGenreFromBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.genreservice.GenreAnalysisGrpc/RemoveGenreFromBook',
            genre__service__pb2.RemoveGenreFromBookRequest.SerializeToString,
            genre__service__pb2.RemoveGenreFromBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGenreGrowth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.genreservice.GenreAnalysisGrpc/GetGenreGrowth',
            genre__service__pb2.GenreGrowthRequest.SerializeToString,
            genre__service__pb2.GenreGrowthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGenrePopularity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.genreservice.GenreAnalysisGrpc/GetGenrePopularity',
            genre__service__pb2.GenrePopularityRequest.SerializeToString,
            genre__service__pb2.GenrePopularityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBooksByGenre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.genreservice.GenreAnalysisGrpc/GetBooksByGenre',
            genre__service__pb2.GetBooksByGenreRequest.SerializeToString,
            genre__service__pb2.GetBooksByGenreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
