# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rating_catalog_pb2 as rating__catalog__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rating_catalog_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RatingCatalogGrpcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRatings = channel.unary_unary(
                '/gateway.ratingcatalog.RatingCatalogGrpc/GetRatings',
                request_serializer=rating__catalog__pb2.GetRatingsRequest.SerializeToString,
                response_deserializer=rating__catalog__pb2.GetRatingsResponse.FromString,
                _registered_method=True)
        self.GetRating = channel.unary_unary(
                '/gateway.ratingcatalog.RatingCatalogGrpc/GetRating',
                request_serializer=rating__catalog__pb2.GetRatingRequest.SerializeToString,
                response_deserializer=rating__catalog__pb2.GetRatingResponse.FromString,
                _registered_method=True)
        self.AddRating = channel.unary_unary(
                '/gateway.ratingcatalog.RatingCatalogGrpc/AddRating',
                request_serializer=rating__catalog__pb2.AddRatingRequest.SerializeToString,
                response_deserializer=rating__catalog__pb2.AddRatingResponse.FromString,
                _registered_method=True)
        self.UpdateRating = channel.unary_unary(
                '/gateway.ratingcatalog.RatingCatalogGrpc/UpdateRating',
                request_serializer=rating__catalog__pb2.UpdateRatingRequest.SerializeToString,
                response_deserializer=rating__catalog__pb2.UpdateRatingResponse.FromString,
                _registered_method=True)
        self.DeleteRating = channel.unary_unary(
                '/gateway.ratingcatalog.RatingCatalogGrpc/DeleteRating',
                request_serializer=rating__catalog__pb2.DeleteRatingRequest.SerializeToString,
                response_deserializer=rating__catalog__pb2.DeleteRatingResponse.FromString,
                _registered_method=True)


class RatingCatalogGrpcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRatings(self, request, context):
        """rpc HealthCheck   (HealthCheckRequest) returns (HealthCheckResponse);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RatingCatalogGrpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRatings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRatings,
                    request_deserializer=rating__catalog__pb2.GetRatingsRequest.FromString,
                    response_serializer=rating__catalog__pb2.GetRatingsResponse.SerializeToString,
            ),
            'GetRating': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRating,
                    request_deserializer=rating__catalog__pb2.GetRatingRequest.FromString,
                    response_serializer=rating__catalog__pb2.GetRatingResponse.SerializeToString,
            ),
            'AddRating': grpc.unary_unary_rpc_method_handler(
                    servicer.AddRating,
                    request_deserializer=rating__catalog__pb2.AddRatingRequest.FromString,
                    response_serializer=rating__catalog__pb2.AddRatingResponse.SerializeToString,
            ),
            'UpdateRating': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRating,
                    request_deserializer=rating__catalog__pb2.UpdateRatingRequest.FromString,
                    response_serializer=rating__catalog__pb2.UpdateRatingResponse.SerializeToString,
            ),
            'DeleteRating': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRating,
                    request_deserializer=rating__catalog__pb2.DeleteRatingRequest.FromString,
                    response_serializer=rating__catalog__pb2.DeleteRatingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gateway.ratingcatalog.RatingCatalogGrpc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gateway.ratingcatalog.RatingCatalogGrpc', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RatingCatalogGrpc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRatings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.ratingcatalog.RatingCatalogGrpc/GetRatings',
            rating__catalog__pb2.GetRatingsRequest.SerializeToString,
            rating__catalog__pb2.GetRatingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.ratingcatalog.RatingCatalogGrpc/GetRating',
            rating__catalog__pb2.GetRatingRequest.SerializeToString,
            rating__catalog__pb2.GetRatingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.ratingcatalog.RatingCatalogGrpc/AddRating',
            rating__catalog__pb2.AddRatingRequest.SerializeToString,
            rating__catalog__pb2.AddRatingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.ratingcatalog.RatingCatalogGrpc/UpdateRating',
            rating__catalog__pb2.UpdateRatingRequest.SerializeToString,
            rating__catalog__pb2.UpdateRatingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gateway.ratingcatalog.RatingCatalogGrpc/DeleteRating',
            rating__catalog__pb2.DeleteRatingRequest.SerializeToString,
            rating__catalog__pb2.DeleteRatingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
