apiVersion: v1
kind: Service
metadata:
  name: author-analytics-service
  namespace: bookcloud
spec:
  selector:
    app: author-analytics-service
  ports:
    - name: grpc
      port: 50056
      targetPort: grpc
  type: ClusterIP
