apiVersion: v1
kind: Service
metadata:
  name: kong
  namespace: bookcloud
spec:
  type: LoadBalancer
  selector:
    app: kong
  ports:
    - name: proxy
      port: 80
      targetPort: proxy
    - name: admin
      port: 8001
      targetPort: admin
