syntax = "proto3";

package gateway.bookcatalog;

import "common.proto";

message Book {
  int64  isbn          = 1;
  string name          = 2;
  string url           = 3;
  string summary_clean = 4;
  int32  pub_year      = 5;
}

message GetBooksRequest {
  int32 page_num = 1;
  int32 page_size = 2;
}

message GetBooksResponse {
  repeated Book books = 1;
  int32 page_num = 2;
  int32 page_size = 3;
  int32 total_items = 4;
  int32 total_pages = 5;
}

service BookCatalogGrpc {
  rpc HealthCheck(gateway.common.HealthCheckRequest) returns (gateway.common.HealthCheckResponse);
  rpc GetBooks(GetBooksRequest) returns (GetBooksResponse);
}
