apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-redis
  namespace: bookcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-redis
  template:
    metadata:
      labels:
        app: book-redis
    spec:
      containers:
        - name: book-redis
          image: redis:7
          ports:
            - name: redis
              containerPort: 6379
          resources:
            requests:
              cpu: "75m"
              memory: "192Mi"
            limits:
              cpu: "700m"
              memory: "1Gi"
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 15
            periodSeconds: 20
