apiVersion: v1
kind: Service
metadata:
  name: book-redis
  namespace: bookcloud
  labels:
    app: book-redis
spec:
  type: ClusterIP
  selector:
    app: book-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
