services:
  author-catalog:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${HOST_GRPC_PORT}:${GRPC_PORT}"
    networks:
      - bookcloud-network
    depends_on:
      - author-db
      - author-redis

  author-db:
    image: postgres:15
    container_name: author-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${HOST_POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - author-db-data:/var/lib/postgresql/data
    networks:
      - bookcloud-network

  author-redis:
    image: redis:7
    container_name: author-redis
    restart: unless-stopped
    ports:
      - "${HOST_REDIS_PORT}:${REDIS_PORT}"
    networks:
      - bookcloud-network

volumes:
  author-db-data:

networks:
  bookcloud-network:
    external: true
