apiVersion: v1
kind: Service
metadata:
  name: rating-db
  namespace: bookcloud
spec:
  selector:
    app: rating-db
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  type: ClusterIP
