services:
  genre-analysis-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${HOST_GRPC_PORT}:${GRPC_PORT}"
    networks:
      - bookcloud-network
  genre-db:
    image: postgres:15
    container_name: genre-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${HOST_POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - genre-db-data:/var/lib/postgresql/data
    networks:
      - bookcloud-network

volumes:
  genre-db-data:

networks:
  bookcloud-network:
    external: true
