services:
  author-analytics-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: author-analytics-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${HOST_GRPC_PORT}:${GRPC_PORT}"
      - "${HOST_HTTP_PORT}:${HTTP_PORT}"
    networks:
      - bookcloud-network

networks:
  bookcloud-network:
    external: true
