syntax = "proto3";
import "common.proto";

package author_catalog;

service AuthorCatalogGrpc {
  rpc GetAuthors(GetAuthorsRequest) returns (GetAuthorsResponse);

  rpc AddAuthor(AddAuthorRequest) returns (AddAuthorResponse);

  rpc UpdateAuthor(UpdateAuthorRequest) returns (UpdateAuthorResponse);

  rpc DeleteAuthor(DeleteAuthorRequest) returns (AuthorDeleteResponse);

  rpc GetAuthor(GetAuthorRequest) returns (GetAuthorResponse);

  rpc HealthCheck (common.HealthCheckRequest) returns (common.HealthCheckResponse);
}

message GetAuthorsRequest{
  optional int64 page = 1;
  optional int64 page_size = 2;
}

message Author {
  int32 id = 1;
  string name = 2;
}

message AddAuthorRequest {
  int32 id = 1;
  string name = 2;
}

message UpdateAuthorResponse {
  repeated Author authors = 1;
}

message UpdateAuthorRequest {
  int32 id = 1;
  optional string name = 2;
}

message AddAuthorResponse {
  Author author = 1;
}

message GetAuthorRequest {
  string author_id = 1;
}

message DeleteAuthorRequest {
  string author_id = 1;
}

message GetAuthorsResponse {
  repeated Author authors = 1;
}

message GetAuthorResponse {
  Author author = 1;
}

message AuthorDeleteResponse {
  bool sucessful = 1;
  string message = 2;
}