syntax = "proto3";

package gateway.authorcatalog;

import "common.proto";

message Author {
  int64 author_id        = 1;
  string name             = 2;
}

message AuthorAdd {
  int64 author_id        = 1;
  string name             = 2;
}

message GetAuthorsRequest  {
  optional int64 page = 1;
  optional int64 page_size = 2;
}

message GetAuthorsResponse { repeated Author authors = 1; }

message GetAuthorRequest   { int64 author_id = 1; }
message GetAuthorResponse  { Author author = 1; }

message AddAuthorRequest   { int64 author_id = 1; string name = 2; }
message AddAuthorResponse  { Author author = 1; }

message UpdateAuthorRequest  {
  int64 author_id = 1;
  optional string name = 2;
}
message UpdateAuthorResponse { repeated Author authors = 1; }

message DeleteAuthorRequest  { int64 author_id = 1; }
message DeleteAuthorResponse {
  bool sucessful = 1;
  string message = 2;
}

message GetAuthorsByNameRequest {
  string name = 1;
}

service AuthorCatalogGrpc {
  rpc HealthCheck  (gateway.common.HealthCheckRequest) returns (gateway.common.HealthCheckResponse);
  rpc GetAuthors   (GetAuthorsRequest)   returns (GetAuthorsResponse);
  rpc GetAuthor    (GetAuthorRequest)    returns (GetAuthorResponse);
  rpc AddAuthor    (AddAuthorRequest)    returns (AddAuthorResponse);
  rpc UpdateAuthor (UpdateAuthorRequest) returns (UpdateAuthorResponse);
  rpc DeleteAuthor (DeleteAuthorRequest) returns (DeleteAuthorResponse);
  rpc GetAuthorsByName(GetAuthorsByNameRequest) returns (GetAuthorsResponse);
}
