syntax = "proto3";
import "common.proto";

package gateway.book_recommendation;

service BookRecommendationGrpc {

  rpc Book_Recommendation(Query) returns (BookRecommendationResponse);

  rpc HealthCheck (common.HealthCheckRequest) returns (common.HealthCheckResponse);
}

message Empty{}

message Query {
  optional string genre = 1;
  optional double rating = 2;
  optional double popularity = 3;
}

message Book {
  int64 isbn = 1;
  string name = 2;
  string url = 3;
  int32 pub_year = 4;
}

message BookRecommendationResponse {
  repeated Book books = 1;
}