apiVersion: apps/v1
kind: Deployment
metadata:
  name: compare-redis
  namespace: bookcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compare-redis
  template:
    metadata:
      labels:
        app: compare-redis
    spec:
      containers:
        - name: compare-redis
          image: redis:7
          ports:
            - name: redis
              containerPort: 6379
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 15
            periodSeconds: 20
