services:
  book-recommendation:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${HOST_GRPC_PORT}:${GRPC_PORT}"
    networks:
      - bookcloud-network

networks:
  bookcloud-network:
    external: true
