apiVersion: v1
kind: Service
metadata:
  name: author-db
  namespace: bookcloud
spec:
  selector:
    app: author-db
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  type: ClusterIP
