apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: book-catalog
  namespace: bookcloud
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: book-catalog
  namespaceSelector:
    matchNames:
      - bookcloud
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
